### ISSUE TITLE
Object.assign is not supported in some browsers

### ISSUE THREAD

**Issue by romelperez** [luisvinicius167/mockschema#2]
Hi,

I am currently testing some [Redux](http://redux.js.org) reducers with [Karma](http://karma-runner.github.io) in [PhantomJS](http://phantomjs.org) but it gives the error:

![selection_001](https://cloud.githubusercontent.com/assets/1393135/21290057/f14510f0-c47a-11e6-9ca9-ce201f024e98.png)

Apparently it does not support [`Object.assign`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) as well as a couple of browsers.

It would be great if the package would be updated to use [extend](https://www.npmjs.com/package/extend) package instead for example.

If you think it is a good idea, I can PR.

**Comment by luisvinicius167** [comment]
@romelperez sounds good! Let me know if you will submit a PR, if not, I can implement this :) Thanks bro!

**Comment by luisvinicius167** [comment]
@romelperez try v0.0.5.

**Comment by romelperez** [comment]
Works great! Thanks!
